# Generated by Django 4.2.7 on 2023-11-14 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_date', models.DateField()),
                ('referrer_name', models.CharField(max_length=100)),
                ('referral_reason', models.TextField()),
                ('note', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='referral_documents/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='healthcare_app.person')),
            ],
        ),
    ]
